# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=10)),
                ('creator', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField()),
                ('path', models.CharField(max_length=50)),
            ],
        ),
    ]
