# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devops_cmdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatetable',
            old_name='path',
            new_name='file_name',
        ),
    ]
