# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devops_cmdb', '0002_auto_20181029_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatetable',
            name='version',
        ),
        migrations.AddField(
            model_name='templatetable',
            name='business',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
