# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops_cmdb', '0003_auto_20181108_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
                ('template_id', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=10)),
                ('file_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='templatetable',
            old_name='create_time',
            new_name='updated_time',
        ),
        migrations.RenameField(
            model_name='templatetable',
            old_name='creator',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='templatetable',
            unique_together=set([('name', 'business')]),
        ),
    ]
