# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devops_cmdb', '0004_auto_20181112_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatetable',
            old_name='updated_time',
            new_name='update_time',
        ),
    ]
