# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-11 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JIRA_FIELDS_CONFIG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(blank=True, null=True, verbose_name='jira project id')),
                ('issue_type_id', models.IntegerField(blank=True, null=True, verbose_name='jira project issue type id')),
                ('fields_config_json', models.CharField(default='', max_length=2000, null=True, verbose_name='字段对应关系json数据')),
            ],
        ),
    ]
