# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-13 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops_jira', '0004_external_system_user_mapping_jira_issues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jira_issues',
            name='project_name',
        ),
        migrations.AddField(
            model_name='jira_issues',
            name='issue_assignee',
            field=models.CharField(max_length=30, null=True, verbose_name='经办人'),
        ),
        migrations.AddField(
            model_name='jira_issues',
            name='issues_id',
            field=models.CharField(max_length=100, null=True, verbose_name='问题类型'),
        ),
        migrations.AddField(
            model_name='jira_issues',
            name='project_key',
            field=models.CharField(max_length=100, null=True, verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='external_system_user_mapping',
            name='external_system',
            field=models.CharField(max_length=255, null=True, verbose_name='外部系统名称'),
        ),
        migrations.AlterField(
            model_name='external_system_user_mapping',
            name='external_system_password',
            field=models.CharField(max_length=255, null=True, verbose_name='外部系统密码'),
        ),
        migrations.AlterField(
            model_name='external_system_user_mapping',
            name='external_system_username',
            field=models.CharField(max_length=255, null=True, verbose_name='外部系统用户名'),
        ),
        migrations.AlterField(
            model_name='external_system_user_mapping',
            name='inner_user_group',
            field=models.CharField(max_length=10, null=True, verbose_name='内部系统账户组'),
        ),
        migrations.AlterField(
            model_name='external_system_user_mapping',
            name='inner_user_name',
            field=models.CharField(max_length=30, null=True, verbose_name='内部系统用户名称'),
        ),
        migrations.AlterField(
            model_name='jira_issues',
            name='inner_user_group',
            field=models.CharField(max_length=10, null=True, verbose_name='内部系统账户组'),
        ),
        migrations.AlterField(
            model_name='jira_issues',
            name='inner_user_name',
            field=models.CharField(max_length=30, null=True, verbose_name='内部系统用户名称'),
        ),
        migrations.AlterField(
            model_name='jira_issues',
            name='issue_create_date',
            field=models.CharField(max_length=15, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='jira_issues',
            name='issue_priority',
            field=models.CharField(max_length=20, null=True, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='jira_issues',
            name='issue_reporter',
            field=models.CharField(max_length=30, null=True, verbose_name='报告人'),
        ),
        migrations.AlterField(
            model_name='jira_issues',
            name='issue_status',
            field=models.CharField(max_length=20, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='jira_issues',
            name='issue_summary',
            field=models.CharField(max_length=200, null=True, verbose_name='主题'),
        ),
        migrations.AlterField(
            model_name='jira_issues',
            name='issue_type',
            field=models.CharField(max_length=100, null=True, verbose_name='问题类型'),
        ),
    ]
