# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-13 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops_jira', '0005_auto_20180513_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jira_issues',
            name='issue_create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='JIRA ISSUE 创建时间'),
        ),
    ]
